services:
  easynode:
    container_name: easynode
    # image: docker.1ms.run/chaoszhu/easynode
    image: docker.cnb.cool/chaoszhu/easynode:latest # cnb自动同步
    restart: always
    ports:
      - 8082:8082 # http建议仅内网访问
      - 8092:8092 # https 端口，访问时需手动加 https://ip:8092
    volumes:
      - /root/easynode/db:/easynode/app/db
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=1
      - GUACD_HOST=easynode-guacd
      - GUACD_PORT=4822
      - HTTP_PORT=8082
      - RDP_PORT=8083
      - ENABLE_HTTPS=1 # 默认自签证书
      - COOKIE_SECURE= false # Session Cookie仅通过HTTPS发送[仅使用 https 访问时请设置为 true]
      - HTTPS_PORT=8092 # https 端口 8092
      - SSL_CERT_PATH=
      - SSL_KEY_PATH=
    depends_on:
      easynode-guacd:
        condition: service_healthy
    networks:
      - easynode-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  easynode-guacd:
    container_name: easynode-guacd
    # image: docker.1ms.run/guacamole/guacd
    image: docker.cnb.cool/chaoszhu/docker-sync-manual/guacamole-guacd:latest_amd64 # cnb加速amd64
    restart: always
    expose:
      - "4822"
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z 127.0.0.1 4822"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks:
      - easynode-network
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  watchtower:
    container_name: easynode-watchtower
    # image: docker.1ms.run/containrrr/watchtower
    image: docker.cnb.cool/chaoszhu/docker-sync-manual/containrrr-watchtower:latest_amd64 # cnb加速amd64
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 */5 * * * *" --label-enable # 每5分钟检测一次更新
    environment:
      - TZ=Asia/Shanghai

networks:
  easynode-network:
    driver: bridge
