name: mobile
description: "EasyNode mobile app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  dio: ^5.7.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  pointycastle: ^3.9.1
  basic_utils: ^5.7.0
  dartssh2: ^2.12.0
  xterm: ^4.0.0
  uuid: ^4.5.1
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_v2_01.png
    - assets/linux.svg
    - assets/windows.svg
